version: '3'

services:
  
  dev:
    image: digiter:latest
    hostname: digiter-dev
    env_file: ops/env.sh
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: ops/Dockerfile
  

  web:
    image: digiter:latest
    hostname: digiter-web
    env_file: ops/env.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"